### ISSUE TITLE
markitondemand API no longer working

### ISSUE THREAD

**Issue by gadgetguy08** [MycroftAI/skill-stock#19]
The site dev.markitondemand.com that provided stock data for this Mycroft skill is no longer functioning.  Therefore the Mycroft skill fails.

**Comment by forslund** [comment]
Thanks for reporting. We'll have to discuss a replacement api. Do you have any suggestions?

**Comment by gadgetguy08** [comment]
Not being a programmer, I am not sure of the effort involved / effectiveness of these solutions, but I see the following:

Yahoo!   an example:  github.com/ranaroussi/yfinance

TwelveData  https://twelvedata.com/

Financial Data Hub   https://finnhub.io/

**Comment by krisgesling** [comment]
We should also extend the tests to ensure we catch this more quickly in the future.
