### ISSUE TITLE
Many stock prices require full names

### ISSUE THREAD

**Issue by gadgetguy08** [MycroftAI/skill-stock#27]
Mycroft Core 20.2.2

Many stock prices require very specific names for a proper response.  
For example, these work without effort:
"Google"  (It reports it as "Alphabet", which is helpful behavior)
"Microsoft"
"Amazon"
"General Electric"
"Apple" 

These require some extra knowledge:
AT&T (also "AT&T Inc" FAILS, haven't found the trick to this one yet)
Altria ("Altria Group" works)
Appian ("Appian Corp" works)
Cisco ("Cisco Systems" works)
IBM ("International Business Machines" works)
Fidelity ("Fidelity Financial" works)
Ford  ("Ford Motor" works)
Verizon ("Verizon Communications" works)

Not sure if there is a way with the API to be less specific, but if not, then a comment in the documentation for the app would be helpful.

**Comment by krisgesling** [comment]
Thanks for reporting this @gadgetguy08 

Have a fix for most of this in the linked PR which explains what's going on. There's actually 3 things!

**Comment by gadgetguy08** [comment]
Thanks for the super quick fix!
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Apr 27, 2020, 16:20 by notifications@github.com:
