### ISSUE TITLE
Never finds stocks

### ISSUE THREAD

**Issue by zenogantner** [MycroftAI/skill-stock#3]
Q: stock price of Alphabet
A: alphabet doesn't exist or has no stock price.

Q: stock price of Google
A: google doesn't exist or has no stock price.

Q: stock price of Apple
A: Sorry, I couldn't find a stock price for apple.

Q: stock price of Microsoft
A: Sorry, I couldn't find a stock price for microsoft.

Is there something wrong with my setup?
I have a freshly installed MyCroft (from github).

**Comment by forslund** [comment]
Closing issue. This was fixed but now is broken again see #19.
